config/routes.rb
Rails.application.routes.draw do

  resources :practitioners
  root 'visitors#index'
  get 'visitors/about'
  get 'visitors/team'
  get 'visitors/price'
  get 'visitors/career'
  get 'visitors/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/practitioner.rb
class Practitioner < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/practitioners_controller.rb
class PractitionersController < ApplicationController
  before_action :set_practitioner, only: [:show, :edit, :update, :destroy]

  # GET /practitioners
  # GET /practitioners.json
  def index
    @practitioners = Practitioner.all
  end

  # GET /practitioners/1
  # GET /practitioners/1.json
  def show
  end

  # GET /practitioners/new
  def new
    @practitioner = Practitioner.new
  end

  # GET /practitioners/1/edit
  def edit
  end

  # POST /practitioners
  # POST /practitioners.json
  def create
    @practitioner = Practitioner.new(practitioner_params)

    respond_to do |format|
      if @practitioner.save
        format.html { redirect_to @practitioner, notice: 'Practitioner was successfully created.' }
        format.json { render :show, status: :created, location: @practitioner }
      else
        format.html { render :new }
        format.json { render json: @practitioner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /practitioners/1
  # PATCH/PUT /practitioners/1.json
  def update
    respond_to do |format|
      if @practitioner.update(practitioner_params)
        format.html { redirect_to @practitioner, notice: 'Practitioner was successfully updated.' }
        format.json { render :show, status: :ok, location: @practitioner }
      else
        format.html { render :edit }
        format.json { render json: @practitioner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /practitioners/1
  # DELETE /practitioners/1.json
  def destroy
    @practitioner.destroy
    respond_to do |format|
      format.html { redirect_to practitioners_url, notice: 'Practitioner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_practitioner
      @practitioner = Practitioner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def practitioner_params
      params.require(:practitioner).permit(:first_name, :last_name, :active, :education, :profession, :provider_number, :email, :phone, :mobile, :address1, :address2, :city, :state, :postcode, :country, :summary, :business_id, :business_name)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
  end

  def about
  end

  def team
  end

  def price
  end

  def career
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/practitioners_helper.rb
module PractitionersHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
    <hr>
  <div class="row">
      <div class="col-md-3">
        <p>Phone</p>
        <p>1300 343 596</p>
      </div>
      <div class="col-md-3">
        <p>Email</p>
        <p>info@example.com</p>
      </div>
      <div class="col-md-3">
        <p>Address</p>
        <p>15 Dobson St,<br>Ascot QLD</p>
      </div>
      <div class="col-md-3">
        <p>Opening hours</p>
        <p>8:00 – 19:00 Mon – Fri <br>
          9:00 – 17:00 Sat</p>
      </div>
  </div>
  <hr>
    <div class="row">
        <div class="col-lg-12">
            <ul class="nav nav-pills nav-justified">
                <li><a href="/">© 2018 Company Name.</a></li>
                <li><a href="#">Terms of Service</a></li>
                <li><a href="#">Privacy</a></li>
            </ul>
        </div>
    </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <div class="container">
    <a class="navbar-brand" href="/"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="<%= root_path %>">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= visitors_about_path %>">About Us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= visitors_team_path %>">Team</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= visitors_price_path %>">Pricing</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= visitors_career_path %>">Career</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Practitioner Login</a>
          </li>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "International" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "A front end application" %>">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>
    <div class="breadcrumb-box">
      <div class="container">
        <%= yield(:breadcrumb) %>
      </div>
    </div>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/practitioners/_form.html.erb
<%= form_with(model: practitioner, local: true, class: "form-horizontal") do |form| %>
  <% if practitioner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(practitioner.errors.count, "error") %> prohibited this practitioner from being saved:</h2>

      <ul>
      <% practitioner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :practitioner_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :practitioner_last_name %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active, id: :practitioner_active %>
  </div>

  <div class="field">
    <%= form.label :education %>
    <%= form.text_field :education, id: :practitioner_education %>
  </div>

  <div class="field">
    <%= form.label :profession %>
    <%= form.text_field :profession, id: :practitioner_profession %>
  </div>

  <div class="field">
    <%= form.label :provider_number %>
    <%= form.text_field :provider_number, id: :practitioner_provider_number %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :practitioner_email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :practitioner_phone %>
  </div>

  <div class="field">
    <%= form.label :mobile %>
    <%= form.text_field :mobile, id: :practitioner_mobile %>
  </div>

  <div class="field">
    <%= form.label :address1 %>
    <%= form.text_field :address1, id: :practitioner_address1 %>
  </div>

  <div class="field">
    <%= form.label :address2 %>
    <%= form.text_field :address2, id: :practitioner_address2 %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :practitioner_city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :practitioner_state %>
  </div>

  <div class="field">
    <%= form.label :postcode %>
    <%= form.text_field :postcode, id: :practitioner_postcode %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, id: :practitioner_country %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_field :summary, id: :practitioner_summary %>
  </div>

  <div class="field">
    <%= form.label :business_id %>
    <%= form.text_field :business_id, id: :practitioner_business_id %>
  </div>

  <div class="field">
    <%= form.label :business_name %>
    <%= form.text_field :business_name, id: :practitioner_business_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/practitioners/edit.html.erb
<h1>Editing Practitioner</h1>

<%= render 'form', practitioner: @practitioner %>

<%= link_to 'Show', @practitioner %> |
<%= link_to 'Back', practitioners_path %>

app/views/practitioners/index.html.erb
<div class="row">
  <div class="col-md-6 col-sm-6 col-6">
    <h1>Handovers</h1>
  </div>
  <div class="col-md-6 col-sm-6 col-6 text-right">
    <a class="btn btn-outline-primary" href="<%= new_practitioner_path %>">New practitioner</a>
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Active</th>
      <th>Profession</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @practitioners.each do |practitioner| %>
      <tr>
        <td><%= practitioner.first_name %></td>
        <td><%= practitioner.last_name %></td>
        <td><%= practitioner.active %></td>
        <td><%= practitioner.profession %></td>
        <td><%= practitioner.email %></td>
        <td><%= link_to 'Show', practitioner %></td>
        <td><%= link_to 'Edit', edit_practitioner_path(practitioner) %></td>
        <td><%= link_to 'Destroy', practitioner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/practitioners/new.html.erb
<h1>New Practitioner</h1>

<%= render 'form', practitioner: @practitioner %>

<%= link_to 'Back', practitioners_path %>

app/views/practitioners/show.html.erb
<div class="row">
  <div class="col-md-6 col-sm-6 col-6">
    <h1>Practitioner</h1>
  </div>
  <div class="col-md-6 col-sm-6 col-6 text-right">
      <a class="btn btn-outline-primary" href="<%= edit_practitioner_path(@practitioner) %>">Edit</a>
  </div>
</div>
<hr>
<p>
  <strong>First name:</strong>
  <%= @practitioner.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @practitioner.last_name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @practitioner.active %>
</p>

<p>
  <strong>Education:</strong>
  <%= @practitioner.education %>
</p>

<p>
  <strong>Profession:</strong>
  <%= @practitioner.profession %>
</p>

<p>
  <strong>Provider number:</strong>
  <%= @practitioner.provider_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @practitioner.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @practitioner.phone %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @practitioner.mobile %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @practitioner.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @practitioner.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @practitioner.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @practitioner.state %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @practitioner.postcode %>
</p>

<p>
  <strong>Country:</strong>
  <%= @practitioner.country %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @practitioner.summary %>
</p>

<p>
  <strong>Business:</strong>
  <%= @practitioner.business_id %>
</p>

<p>
  <strong>Business name:</strong>
  <%= @practitioner.business_name %>
</p>

<%= link_to 'Edit', edit_practitioner_path(@practitioner) %> |
<%= link_to 'Back', practitioners_path %>

app/views/visitors/about.html.erb
<div class="jumbotron sub-hero-background">
  <div class="col-lg-8 col-md-12 col-12">
    <h1 class="subpage-hero-heading">About Us</h1>
  </div>
</div>


<%= render 'visitors/about/intro' %>
<%= render 'visitors/about/benefits' %>

app/views/visitors/about/_benefits.html.erb
<div class="row section-100">
  <div class="col-md-3">
    <h3>Benefit</h3>
    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr.</p>
  </div>
  <div class="col-md-3">
    <h3>Benefit</h3>
    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr.</p>
  </div>
  <div class="col-md-3">
    <h3>Benefit</h3>
    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr.</p>
  </div>
  <div class="col-md-3">
    <h3>Benefit</h3>
    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr.</p>
  </div>
</div>

app/views/visitors/about/_intro.html.erb
<div class="row section-100">
  <div class="col-md-6">
    <h2>About Us:</h2>
    <p>Intense is an independent web design studio with a rich history. It started as a small family-owned business in Oakville, and has grown enough to successfully occupy two large buildings in two different cities.</p>
    <p>Today Intense offers a full range of web design, app development and content marketing services, including building full-featured ecommerce websites and web startups with custom functionality.</p>
  </div>
  <div class="col-md-6">
    <%= image_tag 'about.jpg', class: 'img-responsive', alt: "Mobile Physiotherapist" %>
  </div>
</div>

app/views/visitors/career.html.erb
<div class="jumbotron sub-hero-background">
  <div class="col-lg-8 col-md-12 col-12">
    <h1 class="subpage-hero-heading">Career</h1>
  </div>
</div>

<h1>Visitors#career</h1>
<p>Find me in app/views/visitors/career.html.erb</p>

app/views/visitors/contact.html.erb
<div class="jumbotron sub-hero-background">
  <div class="col-lg-8 col-md-12 col-12">
    <h1 class="subpage-hero-heading">Contact Us</h1>
  </div>
</div>

<%= render 'visitors/contact/contact_details' %>
<%= render 'visitors/contact/contact_form' %>

app/views/visitors/contact/_contact_details.html.erb
  <div class="row">
    <div class="col-md-3">
      <h2>Phone</h2>
      <p>1800 043 234</p>
    </div>
    <div class="col-md-3">
      <h2>Email</h2>
      <p>info@demo.com</p>
    </div>
    <div class="col-md-3">
      <h2>Address</h2>
      <p>213, New Lenox, <br> Chicago, IL 60606</p>
    </div>
    <div class="col-md-3">
      <h2>Opening hours</h2>
      <p>8:00 – 19:00 Mon – Fri <br> 9:00 – 17:00 Sat </p>
    </div>
  </div>

app/views/visitors/contact/_contact_form.html.erb
<h2>Get in touch:</h2>
<form action="/action_page.php">
  <div class="row">
    <div class="form-group col-md-6">
      <label for="email">First name:</label>
      <input type="string" class="form-control" id="first">
    </div>
    <div class="form-group col-md-6">
      <label for="pwd">Last name:</label>
      <input type="string" class="form-control" id="last">
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-6">
      <label for="email">Phone:</label>
      <input type="string" class="form-control" id="first">
    </div>
    <div class="form-group col-md-6">
      <label for="pwd">Email:</label>
      <input type="string" class="form-control" id="last">
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <label for="pwd">Message:</label>
      <input type="string" class="form-control" id="message">
    </div>
  </div>
  <br>
  <button type="submit" class="btn btn btn-primary">Submit</button>
</form>

app/views/visitors/index.html.erb
<%= render 'visitors/index/hero' %>

<%= render 'visitors/index/how_it_works' %>

<%= render 'visitors/index/index_paragraph' %>

<%= render 'visitors/index/call_to_action' %>

<%= render 'visitors/index/team' %>

<%= render 'visitors/index/service_area' %>

<%= render 'visitors/index/call_to_action' %>

app/views/visitors/index/_call_to_action.html.erb
<div class="section-100">
  <h3>Book appointment online</h3>
  <br>
  <button type="button" class="btn btn-success">Success</button>
</div>

app/views/visitors/index/_hero.html.erb
<div class="jumbotron hero-background">
  <div class="col-lg-8 col-md-12 col-12">
    <h1 class="display-2 hero-heading">Business Name</h1>
    <p class="lead hero-subheading">
      Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor.
    </p>
  </div>
</div>

app/views/visitors/index/_how_it_works.html.erb
  <div class="row section-100">
    <div class="col-md-3">
      <h4>Search local area</h4>
      <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr.</p>
    </div>
    <div class="col-md-3">
      <h4>Select practitioner</h4>
      <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr.</p>
    </div>
    <div class="col-md-3">
      <h4>Book online</h4>
      <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr.</p>
    </div>
    <div class="col-md-3">
      <h4>Home Visit</h4>
      <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr.</p>
    </div>
  </div>

app/views/visitors/index/_index_paragraph.html.erb
<div class="row">
  <div class="col-md-6">
    <h2>Why Business Name?</h2>
    <p>Intense is an independent web design studio with a rich history. It started as a small family-owned business in Oakville, and has grown enough to successfully occupy two large buildings in two different cities.</p>
    <p>Today Intense offers a full range of web design, app development and content marketing services, including building full-featured ecommerce websites and web startups with custom functionality.</p>
  </div>
  <div class="col-md-6">
    <%= image_tag 'about.jpg', class: 'img-responsive', alt: "Mobile Physiotherapist" %>
  </div>
</div>

app/views/visitors/index/_service_area.html.erb
<div class="row section-100">
  <div class="col-md-6">
    <%= image_tag 'about.jpg', class: 'img-responsive', alt: "Mobile Physiotherapist" %>
  </div>
  <div class="col-md-6">
    <h2>Service area</h2>
    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
  </div>
</div>

app/views/visitors/index/_team.html.erb
<h2>Our team</h2>
<hr>
<div class="row">
  <div class="col-md-3">
    <%= render 'visitors/team/practitioner' %>
  </div>
  <div class="col-md-3">
    <%= render 'visitors/team/practitioner' %>
  </div>
  <div class="col-md-3">
    <%= render 'visitors/team/practitioner' %>
  </div>
  <div class="col-md-3">
    <%= render 'visitors/team/practitioner' %>
  </div>
</div>

app/views/visitors/price.html.erb
<div class="jumbotron sub-hero-background">
  <div class="col-lg-8 col-md-12 col-12">
    <h1 class="subpage-hero-heading">Pricing</h1>
  </div>
</div>

<%= render 'visitors/price/table' %>

app/views/visitors/price/_table.html.erb
<h1>Pricing</h1>
<p>Each practitioner can set their own pricing</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Practitioners</th>
      <th>Billable items</th>
      <th>Item Number</th>
      <th>Price</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td>Ben Strachan</td>
        <td>Initial home visit</td>
        <td>500</td>
        <td>$130</td>
      </tr>
  </tbody>
</table>

<br>

app/views/visitors/team.html.erb
<div class="jumbotron sub-hero-background">
  <div class="col-lg-8 col-md-12 col-12">
    <h1 class="subpage-hero-heading">Team</h1>
  </div>
</div>

<h2>Our team</h2>
<hr>
<div class="row">
  <div class="col-md-3">
    <%= render 'visitors/team/practitioner' %>
  </div>
  <div class="col-md-3">
    <%= render 'visitors/team/practitioner' %>
  </div>
  <div class="col-md-3">
    <%= render 'visitors/team/practitioner' %>
  </div>
  <div class="col-md-3">
    <%= render 'visitors/team/practitioner' %>
  </div>
  <div class="col-md-3">
    <%= render 'visitors/team/practitioner' %>
  </div>
  <div class="col-md-3">
    <%= render 'visitors/team/practitioner' %>
  </div>
  <div class="col-md-3">
    <%= render 'visitors/team/practitioner' %>
  </div>
</div>

app/views/visitors/team/_practitioner.html.erb
<div class="section-15 text-center">
  <%= image_tag 'team.jpg', class: 'img-responsive', alt: "Mobile Physiotherapist" %>
  <p>Ben Strachan <br>Physiotherapist <br>Ascot, QLD </p>
</div>